### ISSUE TITLE
'Hardswish' object has no attribute 'inplace'

### ISSUE THREAD

**Issue by RifatSanaullah** [bharatsubedi/ALPR-Yolov5#10]
I am facing this error when trying to run combine_test.py

device: cpu
Fusing layers... 
Fusing layers... 
Traceback (most recent call last):
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/combine_test.py", line 116, in <module>
    detect()
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/combine_test.py", line 95, in detect
    pred = model(img, augment=False)[0]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/models/yolo.py", line 107, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/models/yolo.py", line 127, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/models/common.py", line 87, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Brain Station 23/RnD Lab/Augustus/License Plate detection/ALPR-Yolov5/end-t-end-test/models/common.py", line 29, in forward
    return self.act(self.bn(self.conv(x)))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/activation.py", line 461, in forward
    return F.hardswish(input, self.inplace)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Hardswish' object has no attribute 'inplace'

**Comment by Aksh97** [comment]
Any update on this?

**Comment by bharatsubedi** [comment]
@Aksh97 error occurs due to different versions of PyTorch. If you use the same version no errors will be there.
