### ISSUE TITLE
Error AttributeError: 'Hardswish' object has no attribute 'inplace'

### ISSUE THREAD

**Issue by MyraBaba** [bharatsubedi/ALPR-Yolov5#17]
install requirements and run end-t-end-test gives error:

AttributeError: 'Hardswish' object has no attribute 'inplace'

all models in correct place.

ubuntu 18 and python 3.8.5

`Traceback (most recent call last):
  File "combine_test.py", line 117, in <module>
    detect()
  File "combine_test.py", line 77, in detect
    _ = model_reco(img.half() if half else img) if device.type != 'cpu' else None
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/dProjects/ALPR-Yolov5/end-t-end-test/models/yolo.py", line 107, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/data/dProjects/ALPR-Yolov5/end-t-end-test/models/yolo.py", line 127, in forward_once
    x = m(x)  # run
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/dProjects/ALPR-Yolov5/end-t-end-test/models/common.py", line 87, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/dProjects/ALPR-Yolov5/end-t-end-test/models/common.py", line 29, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 472, in forward
    return F.hardswish(input, self.inplace)
  File "/home/alp2080/Projects/Yolov5_StrongSORT_OSNet/venvStrongSort/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Hardswish' object has no attribute 'inplace'`

> Package                 Version
----------------------- --------------------
absl-py                 1.2.0
asttokens               2.1.0
backcall                0.2.0
beautifulsoup4          4.11.1
cachetools              5.2.0
certifi                 2022.6.15
charset-normalizer      2.1.0
cycler                  0.11.0
Cython                  0.29.30
decorator               5.1.1
easydict                1.9
executing               1.2.0
filelock                3.7.1
flake8                  4.0.1
fonttools               4.34.4
future                  0.18.2
gdown                   4.5.1
google-auth             2.9.1
google-auth-oauthlib    0.4.6
grpcio                  1.47.0
h5py                    3.7.0
idna                    3.3
imageio                 2.19.5
importlib-metadata      4.12.0
ipython                 8.6.0
isort                   4.3.21
jedi                    0.18.1
kiwisolver              1.4.4
Markdown                3.4.1
matplotlib              3.5.2
matplotlib-inline       0.1.6
mccabe                  0.6.1
numpy                   1.23.1
oauthlib                3.2.0
onnx                    1.12.0
opencv-python           4.6.0.66
packaging               21.3
pafy                    0.5.5
pandas                  1.4.3
parso                   0.8.3
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.2.0
pip                     20.0.2
pkg-resources           0.0.0
prompt-toolkit          3.0.32
protobuf                3.19.4
psutil                  5.9.4
ptyprocess              0.7.0
pure-eval               0.2.2
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycodestyle             2.8.0
pyflakes                2.4.0
Pygments                2.13.0
pyparsing               3.0.9
PySocks                 1.7.1
python-dateutil         2.8.2
pytz                    2022.1
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.8
scipy                   1.8.1
seaborn                 0.11.2
setuptools              44.0.0
six                     1.16.0
soupsieve               2.3.2.post1
stack-data              0.6.1
tb-nightly              2.10.0a20220719
tensorboard             2.11.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
thop                    0.1.1.post2209072238
torch                   1.12.0
torchvision             0.13.0
tqdm                    4.64.0
traitlets               5.5.0
typing-extensions       4.3.0
urllib3                 1.26.10
wcwidth                 0.2.5
Werkzeug                2.1.2
wheel                   0.37.1
yacs                    0.1.8
yapf                    0.32.0
youtube-dl              2020.12.2
zipp                    3.8.1

**Comment by bharatsubedi** [comment]
this is due to pytorch version. Please check previous comments and pytorch version I used and run it again.

**Comment by MyraBaba** [comment]
I tried a few but same error.

Would you mind to share a working versions exactly ? better output of the pip list :)

**Comment by bharatsubedi** [comment]
Please check on readme file. I already mention there.
